name: StressWatch
channels: 
- conda-forge
dependencies:
- python=3.8
- conda
- pandas
- numpy
- scipy
- scikit-learn
- tensorflow
- keras
- seaborn=0.10.0 
- joblib=0.15.1
- matplotlib=3.2.1
- pickle
- pip
- pip:
  - streamlit
