name: StressWatch
channels: 
- conda-forge
dependencies:
- python=3.8
- conda
- pandas
- numpy
- scipy
- scikit-learn
- seaborn
- tensorflow=2.2.0
- keras=2.3.1  
- joblib
- matplotlib
- datetime
- pip
- pip:
  - streamlit
  - pickleshare

