name: StressWatch
channels: 
- conda-forge
dependencies:
- python=3.8
- conda
- pandas
- numpy
- scipy
- scikit-learn
- tensorflow
- keras
- seaborn
- joblib
- pickle
- pip
- pip:
  - streamlit
  - joblib
  - matplotlib
