name: StressWatch
channels: 
- conda-forge
dependencies:
- python=3.8
- conda
- pandas
- numpy
- scipy
- scikit-learn
- tensorflow
- keras
- seaborn 
- joblib
- matplotlib
- pickle
- pip
- pip:
  - streamlit
